name: req_livestream_helper
description: "A new Flutter project."
publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.3.6
  excel: ^2.0.6
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  window_size: ^0.1.0
  intl: ^0.20.2
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml